"""Canonical AI-tool catalog for the T1-A-000 tool inventory question.

Grouped by category for visual rendering.

Total: 317 tools across 23 categories.
Source: SRJ_AI_Tool_Inventory_Tracker_Upgraded_2026.csv (Stephen, 2026-07-20).
Regenerate with the build script rather than hand-editing, so this file
and the operator CSV can never drift apart.

Any tool the respondent uses that is not listed here goes into the
free-form "other" text field on the inventory question.

CATEGORIES is the primary data structure the partial iterates over.
TOOLS_FLAT is a convenience flat list (used by T1-B-017 row prefill).
"""

from __future__ import annotations

from typing import List, Tuple


CATEGORIES: List[Tuple[str, List[str]]] = [
    ('Chat & General LLMs', [
        '01.AI Yi',
        'AI2 OLMo',
        'Aleph Alpha',
        'Apple Intelligence',
        'Baichuan',
        'Cerebras',
        'Character.ai',
        'ChatGPT',
        'Claude',
        'Cohere Coral',
        'Databricks DBRX',
        'DeepSeek',
        'Falcon (TII)',
        'Fireworks AI',
        'Gemini',
        'Grok',
        'Huawei PanGu',
        'HyperWrite',
        'InternLM (Shanghai AI Lab)',
        'JAIS (G42 / Inception)',
        'Janitor AI',
        'Kimi',
        'LMSYS Arena Models',
        'Llama (Meta)',
        'Microsoft Copilot',
        'Mistral / Le Chat',
        'NVIDIA Nemotron',
        'Notion AI',
        'Perplexity AI',
        'Pi',
        'Poe',
        'Replicate',
        'SambaNova',
        'Samsung Gauss',
        'SaulLM (Saul)',
        'SenseTime SenseChat',
        'Slack AI',
        'Snowflake Arctic',
        'Together AI',
        'You.com',
        'Zoom AI Companion',
        'iFlytek Spark',
    ]),
    ('Chinese Foundation Models', [
        'Doubao / Seed (ByteDance)',
        'ERNIE (Baidu)',
        'GLM / Z.AI (Zhipu AI)',
        'Hunyuan (Tencent)',
        'MiMo (Xiaomi)',
        'MiniMax',
        'Qwen / Tongyi Qianwen (Alibaba)',
    ]),
    ('Writing & Editing', [
        'Anyword',
        'Clearscope',
        'Copy.ai',
        'Frase',
        'Grammarly',
        'Jasper',
        'Jasper Campaigns',
        'MarketMuse',
        'QuillBot',
        'Rytr',
        'Surfer SEO',
        'Typeface',
        'Wordtune',
        'WriteSonic',
        'Writer.com',
    ]),
    ('Notes, Knowledge & Meetings', [
        'Asana AI',
        'Avoma',
        'Box AI',
        'Cisco Webex AI',
        'ClickUp AI',
        'Coda AI',
        'Confluence AI',
        'Dropbox AI',
        'Fathom',
        'Fireflies.ai',
        'Gong',
        'Google Drive AI',
        'Google Meet AI',
        'Grain',
        'Logseq AI',
        'Mem',
        'Microsoft Teams AI',
        'Monday.com AI',
        'NotebookLM',
        'Notion Q&A',
        'Obsidian AI',
        'Otter.ai',
        'Read.ai',
        'SharePoint AI',
        'Supernormal',
        'Trello AI (Atlassian)',
        'tl;dv',
    ]),
    ('Image & Graphic Design', [
        'Adobe Express AI',
        'Adobe Firefly',
        'Blender AI Add-ons',
        'Canva AI',
        'Clipdrop (Stability AI)',
        'DALL-E (OpenAI)',
        'DeepAI',
        'Figma AI',
        'Freepik AI',
        'Ideogram',
        'Jasper Art',
        'Krita AI',
        'Leonardo.ai',
        'Microsoft Designer',
        'Midjourney',
        'Miro AI',
        'Photoroom',
        'Recraft',
        'Remove.bg',
        'Sketch AI',
        'Stable Diffusion',
    ]),
    ('Video Generation & Editing', [
        '2short.ai',
        'CapCut',
        'Captions AI',
        'Colossyan',
        'D-ID',
        'DaVinci Resolve AI',
        'Descript',
        'Elai.io',
        'Filmora AI',
        'Final Cut Pro AI',
        'Fliki',
        'Hailuo AI (MiniMax)',
        'Headliner',
        'HeyGen',
        'Hour One',
        'InShot AI',
        'InVideo',
        'Kling AI (Kuaishou)',
        'Krea AI',
        'Loom AI',
        'Luma AI',
        'Lumen5',
        'Microsoft Clipchamp AI',
        'Munch',
        'OpusClip',
        'Pictory',
        'Pika Labs',
        'Premiere Pro AI (Adobe)',
        'Repurpose.io',
        'Runway',
        'Sora (OpenAI)',
        'Splice',
        'Submagic',
        'Synthesia',
        'Veed.io AI',
        'Videoleap',
        'Vidu (Tsinghua / Shengshu)',
        'Vizard AI',
        'Wavve',
        'Wistia',
        'Wondershare Virbo',
        'Zeemo',
        'iMovie AI',
    ]),
    ('Voice & Audio', [
        'AIVA',
        'Adobe Podcast AI',
        'Altered',
        'AssemblyAI',
        'Deepgram',
        'Descript Overdub',
        'ElevenLabs',
        'Krisp',
        'Lovo (Genny)',
        'Murf.ai',
        'Play.ht',
        'Resemble AI',
        'Respeecher',
        'Rev AI',
        'Soundraw',
        'Speechmatics',
        'Suno',
        'Udio',
        'Voicemod',
        'Whisper API (OpenAI)',
    ]),
    ('Slides & Presentations', [
        'Beautiful.ai',
        'Decktopus',
        'Gamma',
        'Pitch AI',
        'Presentations.AI',
        'SlidesAI',
        'Tome',
    ]),
    ('Coding & Developer Tools', [
        'Anthropic Console',
        'AutoGen (Microsoft)',
        'Bolt.new',
        'Chroma',
        'Claude Code',
        'Comet ML',
        'CrewAI',
        'Cursor',
        'DSPy',
        'Dify',
        'Flowise',
        'GitHub Copilot',
        'Google AI Studio',
        'Hugging Face',
        'LangChain',
        'LlamaIndex',
        'Lovable',
        'Neptune.ai',
        'OpenAI API / GPT models',
        'OpenAI Playground / Dashboard',
        'Pinecone',
        'Relevance AI',
        'Replit Agent',
        'Stack AI',
        'Tabnine',
        'Voiceflow',
        'Weaviate',
        'Weights & Biases',
        'Windsurf',
        'v0 (Vercel)',
    ]),
    ('Automation & Agents', [
        'Apify',
        'Automation Anywhere',
        'Bardeen',
        'Blue Prism',
        'Browse AI',
        'Make (Integromat) AI',
        'Manus',
        'Microsoft Power Automate AI',
        'UiPath AI',
        'Zapier AI',
        'Zapier Central',
        'n8n',
    ]),
    ('Search, Research, Translation & Other', [
        'Connected Papers',
        'Consensus',
        'DeepL',
        'Elicit',
        'Groq',
        'Lokalise AI',
        'Perplexity Enterprise Pro',
        'Phrase (Memsource)',
        'ResearchRabbit',
        'Salesforce Einstein / Agentforce',
        'Scite',
        'Semantic Scholar',
        'Smartcat',
        'Unbabel',
        'Wayground',
        'You.com Enterprise',
    ]),
    ('AI Governance & Risk Management Platforms', [
        'Arize AI',
        'Arthur AI',
        'Credo AI',
        'Fiddler AI',
        'Holistic AI',
        'IBM OpenPages with Watson',
        'Monitaur',
        'OneTrust AI Governance',
        'ServiceNow AI Governance',
        'WhyLabs',
    ]),
    ('Cloud AI Services & Model APIs', [
        'AI21 Labs API',
        'AWS Bedrock',
        'Amazon SageMaker',
        'Azure Machine Learning',
        'Azure OpenAI Service',
        'Cohere API',
        'Google Vertex AI',
        'IBM watsonx',
        'NVIDIA NIM',
    ]),
    ('Data & Analytics AI', [
        'Alteryx AI',
        'Databricks AI / DBRX',
        'Dataiku',
        'Palantir AIP',
        'Snowflake Cortex',
        'Tableau AI (Einstein)',
    ]),
    ('ERP & Business Application AI', [
        'Oracle Fusion AI',
        'SAP Joule',
        'ServiceNow Now Assist',
        'Workday AI',
    ]),
    ('Education & Research AI', [
        'CheggMate',
        'Grammarly for Education',
        'Khanmigo (Khan Academy)',
        'Turnitin AI Detection',
    ]),
    ('Emerging / Frontier AI', [
        'Cohere Command R+',
        'Computer Use (Anthropic)',
        'Devin (Cognition)',
        'Figure AI',
        'Mistral Large 2',
        'Operator (OpenAI)',
        'Physical Intelligence (pi0)',
        'Tesla Optimus',
    ]),
    ('Enterprise AI Platforms & Agent Orchestration', [
        'Aisera',
        'Cognigy',
        'Decagon',
        'Glean',
        'Kore.ai',
        'Moveworks',
        'Sierra',
        'Vellum',
    ]),
    ('Finance & Legal AI', [
        'AlphaSense',
        'Bloomberg GPT',
        'CoCounsel (Casetext)',
        'Harvey AI',
        'Kira Systems',
        'Vanta',
    ]),
    ('HR & Talent AI', [
        'Beamery',
        'Eightfold AI',
        'HireVue',
        'LinkedIn Recruiter AI',
        'Paradox (Olivia)',
    ]),
    ('Healthcare & Life Sciences AI', [
        'Epic AI (SlicerDicer, etc.)',
        'Google Med-PaLM / MedLM',
        'Insilico Medicine',
        'Merative (formerly Watson Health)',
        'Tempus AI',
    ]),
    ('Open Source & Self-Hosted Models', [
        'Hugging Face Transformers',
        'Ollama',
        'PyTorch',
        'TensorFlow / Keras',
        'llama.cpp',
        'vLLM',
    ]),
    ('Security & Identity AI', [
        'CrowdStrike Charlotte AI',
        'Darktrace',
        'Okta AI',
        'Palo Alto Networks Precision AI',
        'SentinelOne Purple AI',
        'Zscaler AI',
    ]),
]


TOOLS_FLAT: List[str] = [tool for _, tools in CATEGORIES for tool in tools]
